nkeymap('<Leader>g', '<Cmd>Telescope find_files<Cr>')
nkeymap('<Leader>f', '<Cmd>Telescope git_files<Cr>')
nkeymap('<Leader>z', '<Cmd>Telescope current_buffer_fuzzy_find<Cr>')
nkeymap('<Leader>r', '<Cmd>Telescope registers<Cr>')
nkeymap('<Leader>o', '<Cmd>Telescope coc diagnostics<Cr>')
nkeymap('<Leader>e', '<Cmd>Telescope treesitter<Cr>')
nkeymap('<Leader>l', '<Cmd>Telescope buffers<Cr>')
nkeymap('<Leader>s', '<Cmd>Telescope spell_suggest<Cr>')
